import React, { useState, useEffect, useCallback } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { getBookingsByEmail, updateBookingStatus } from "../api/travelApi";

const statusConfig = {
  PENDING:   { bg: "bg-amber-50",  text: "text-amber-700",  border: "border-amber-200", dot: "bg-amber-400",  label: "Pending",   icon: "⏳" },
  CONFIRMED: { bg: "bg-emerald-50",text: "text-emerald-700",border: "border-emerald-200",dot: "bg-emerald-500",label: "Confirmed", icon: "✅" },
  CANCELLED: { bg: "bg-red-50",    text: "text-red-600",    border: "border-red-200",    dot: "bg-red-400",    label: "Cancelled", icon: "✗" },
};

const categoryEmoji = {
  TEMPLES: "🛕", HILLS: "⛰️", FORESTS: "🌿", BEACHES: "🏖️",
  temples: "🛕", hills: "⛰️", forests: "🌿", beaches: "🏖️",
};

export default function BookingsPage() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [bookings, setBookings] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [activeTab, setActiveTab] = useState("upcoming");
  const [searchQuery, setSearchQuery] = useState("");
  const [cancellingId, setCancellingId] = useState(null);
  const [showCancelModal, setShowCancelModal] = useState(null);

  const fetchBookings = useCallback(async () => {
    if (!user?.email) return;
    setLoading(true);
    setError("");
    try {
      const res = await getBookingsByEmail(user.email);
      setBookings(Array.isArray(res.data) ? res.data : []);
    } catch {
      setBookings([]);
      setError("Could not fetch bookings. Please check your connection and try again.");
    } finally {
      setLoading(false);
    }
  }, [user?.email]);

  useEffect(() => { fetchBookings(); }, [fetchBookings]);

  const handleCancel = async (bookingId) => {
    setCancellingId(bookingId);
    try {
      await updateBookingStatus(bookingId, "CANCELLED");
      setBookings(prev => prev.map(b => b.id === bookingId ? { ...b, status: "CANCELLED" } : b));
    } catch {
      alert("Could not cancel booking. Please try again.");
    } finally {
      setCancellingId(null);
      setShowCancelModal(null);
    }
  };

  const handleDownload = (booking) => {
    const dest = booking.destination;
    const content = `VTRAVEL TRIP PLAN
====================
Booking Ref: #${booking.id}
Status: ${booking.status}

DESTINATION
-----------
Name: ${dest?.name || "N/A"}
Location: ${dest?.location || "N/A"}
Category: ${dest?.category || "N/A"}
Rating: ★ ${dest?.rating || "N/A"}

TRIP DETAILS
------------
Travel Date: ${booking.travelDate}
Duration: ${booking.duration || dest?.duration || "N/A"}
Starting From: ${booking.currentLocation || "N/A"}
Estimated Budget: ${booking.budget || dest?.budget || "N/A"}

DESTINATION INFO
----------------
Best Time: ${dest?.bestTime || "N/A"}
Difficulty: ${dest?.difficulty || "N/A"}

${dest?.description ? "About: " + dest.description + "\n" : ""}
${booking.specialRequirements ? "Special Requirements: " + booking.specialRequirements + "\n" : ""}
Generated by V_Travel — Your Solo Travel Companion`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `V_Travel_Trip_${dest?.name?.replace(/\s+/g, "_")}_${booking.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const filtered = bookings.filter(b => {
    const travelDate = b.travelDate ? new Date(b.travelDate) : null;
    const matchesSearch = !searchQuery ||
      (b.destination?.name || "").toLowerCase().includes(searchQuery.toLowerCase()) ||
      (b.destination?.location || "").toLowerCase().includes(searchQuery.toLowerCase()) ||
      (b.currentLocation || "").toLowerCase().includes(searchQuery.toLowerCase());

    if (!matchesSearch) return false;

    if (activeTab === "upcoming") {
      return b.status !== "CANCELLED" && (!travelDate || travelDate >= today);
    } else if (activeTab === "completed") {
      return b.status !== "CANCELLED" && travelDate && travelDate < today;
    } else {
      return b.status === "CANCELLED";
    }
  });

  const counts = {
    upcoming: bookings.filter(b => {
      const d = b.travelDate ? new Date(b.travelDate) : null;
      return b.status !== "CANCELLED" && (!d || d >= today);
    }).length,
    completed: bookings.filter(b => {
      const d = b.travelDate ? new Date(b.travelDate) : null;
      return b.status !== "CANCELLED" && d && d < today;
    }).length,
    cancelled: bookings.filter(b => b.status === "CANCELLED").length,
  };

  const tabs = [
    { id: "upcoming",  label: "Upcoming",  icon: "🗺️", count: counts.upcoming },
    { id: "completed", label: "Completed", icon: "✅", count: counts.completed },
    { id: "cancelled", label: "Cancelled", icon: "✗",  count: counts.cancelled },
  ];

  return (
    <div className="min-h-screen bg-earth-50 pt-20">
      {/* ─── Hero Banner ───────────────────────────────────────────── */}
      <div className="bg-earth-900 text-white">
        <div className="max-w-5xl mx-auto px-4 py-10">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <p className="text-saffron-400 text-sm font-medium uppercase tracking-widest mb-1">Your Journey</p>
              <h1 className="font-display text-3xl sm:text-4xl font-bold">My Bookings</h1>
              {user?.name && (
                <p className="text-earth-400 mt-1.5 text-sm">
                  Welcome back, <span className="text-white font-medium">{user.name}</span>
                </p>
              )}
            </div>
            {/* Stats */}
            {!loading && bookings.length > 0 && (
              <div className="flex gap-5">
                {[
                  { label: "Total", val: bookings.length, color: "text-white" },
                  { label: "Upcoming", val: counts.upcoming, color: "text-saffron-400" },
                  { label: "Completed", val: counts.completed, color: "text-emerald-400" },
                ].map(s => (
                  <div key={s.label} className="text-center">
                    <div className={`font-display text-2xl font-bold ${s.color}`}>{s.val}</div>
                    <div className="text-earth-500 text-xs uppercase tracking-wide">{s.label}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 py-8">
        {/* ─── Search + Plan Trip Button ─────────────────────────── */}
        <div className="flex flex-col sm:flex-row gap-3 mb-6">
          <div className="relative flex-1">
            <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-earth-400 text-sm">🔍</span>
            <input
              type="text"
              placeholder="Search destinations, locations…"
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2.5 bg-white border border-earth-200 rounded-xl text-sm focus:outline-none focus:border-saffron-400 text-earth-800 placeholder:text-earth-400"
            />
          </div>
          <Link
            to="/plan"
            className="flex-shrink-0 bg-saffron-600 hover:bg-saffron-500 text-white text-sm font-medium px-5 py-2.5 rounded-xl transition-all text-center"
          >
            + Plan New Trip
          </Link>
        </div>

        {/* ─── Tabs ──────────────────────────────────────────────── */}
        <div className="flex gap-1 bg-white border border-earth-200 rounded-xl p-1 mb-6 w-fit">
          {tabs.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                activeTab === tab.id
                  ? "bg-earth-900 text-white shadow-sm"
                  : "text-earth-600 hover:bg-earth-50"
              }`}
            >
              <span className="text-xs">{tab.icon}</span>
              {tab.label}
              <span className={`text-xs px-1.5 py-0.5 rounded-full ${
                activeTab === tab.id ? "bg-white/20 text-white" : "bg-earth-100 text-earth-500"
              }`}>
                {tab.count}
              </span>
            </button>
          ))}
        </div>

        {/* ─── Loading ───────────────────────────────────────────── */}
        {loading && (
          <div className="text-center py-20 text-earth-400">
            <div className="text-4xl animate-pulse mb-3">✦</div>
            <p className="text-sm">Loading your trips…</p>
          </div>
        )}

        {/* ─── Error ─────────────────────────────────────────────── */}
        {!loading && error && (
          <div className="bg-red-50 border border-red-200 text-red-600 rounded-xl px-4 py-3 mb-6 text-sm flex items-center justify-between">
            <span>{error}</span>
            <button onClick={fetchBookings} className="ml-4 underline font-medium flex-shrink-0">Retry</button>
          </div>
        )}

        {/* ─── Empty State ───────────────────────────────────────── */}
        {!loading && !error && filtered.length === 0 && (
          <div className="text-center py-20 bg-white rounded-2xl border border-earth-100">
            <div className="text-5xl mb-4">
              {activeTab === "upcoming" ? "🗺️" : activeTab === "completed" ? "✅" : "❌"}
            </div>
            <h3 className="font-display text-xl text-earth-800 mb-2">
              {searchQuery ? "No matches found" :
               activeTab === "upcoming" ? "No upcoming trips" :
               activeTab === "completed" ? "No completed trips yet" :
               "No cancelled trips"}
            </h3>
            <p className="text-earth-500 text-sm mb-6">
              {searchQuery ? "Try a different search term." :
               activeTab === "upcoming" ? "Start planning your next adventure!" : ""}
            </p>
            {!searchQuery && activeTab === "upcoming" && (
              <Link to="/" className="inline-block bg-saffron-600 text-white px-6 py-2.5 rounded-full text-sm font-medium hover:bg-saffron-500 transition-all">
                Explore Destinations →
              </Link>
            )}
          </div>
        )}

        {/* ─── Booking Cards ─────────────────────────────────────── */}
        {!loading && !error && filtered.length > 0 && (
          <div className="space-y-4">
            <p className="text-earth-500 text-xs font-medium uppercase tracking-wide">
              {filtered.length} trip{filtered.length !== 1 ? "s" : ""}
            </p>

            {filtered.map(b => {
              const dest = b.destination || {};
              const sc = statusConfig[b.status] || statusConfig.PENDING;
              const catEmoji = categoryEmoji[dest.category] || "📍";

              return (
                <div key={b.id} className="bg-white rounded-2xl border border-earth-100 shadow-sm overflow-hidden hover:shadow-md transition-shadow">
                  <div className="flex gap-0 sm:gap-4">
                    {/* Image */}
                    <div className="relative w-28 sm:w-40 flex-shrink-0 overflow-hidden">
                      {dest.imageUrl ? (
                        <img
                          src={dest.imageUrl}
                          alt={dest.name}
                          className="w-full h-full object-cover"
                          style={{ minHeight: "140px" }}
                        />
                      ) : (
                        <div className="w-full h-full bg-earth-100 flex items-center justify-center text-4xl" style={{ minHeight: "140px" }}>
                          {catEmoji}
                        </div>
                      )}
                      {/* Status dot */}
                      <div className={`absolute top-2 left-2 w-2 h-2 rounded-full ${sc.dot}`} />
                    </div>

                    {/* Content */}
                    <div className="flex-1 p-4 min-w-0">
                      <div className="flex items-start justify-between gap-2 flex-wrap mb-1">
                        <div>
                          <h3 className="font-semibold text-earth-900 text-base leading-tight">{dest.name || "Destination"}</h3>
                          <p className="text-earth-500 text-xs mt-0.5">{catEmoji} {dest.category} · 📍 {dest.location}</p>
                        </div>
                        <span className={`text-xs px-2.5 py-1 rounded-full border font-medium flex-shrink-0 ${sc.bg} ${sc.text} ${sc.border}`}>
                          {sc.icon} {sc.label}
                        </span>
                      </div>

                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-3">
                        {[
                          { icon: "📅", label: "Travel Date", val: b.travelDate || "—" },
                          { icon: "⏱", label: "Duration", val: b.duration || dest.duration || "—" },
                          { icon: "💰", label: "Budget", val: b.budget || dest.budget?.split(/[–-]/)[0] || "—" },
                          { icon: "📍", label: "From", val: b.currentLocation || "—" },
                        ].map(item => (
                          <div key={item.label} className="bg-earth-50 rounded-lg px-2.5 py-1.5">
                            <p className="text-earth-400 text-xs">{item.icon} {item.label}</p>
                            <p className="text-earth-800 text-xs font-medium truncate mt-0.5">{item.val}</p>
                          </div>
                        ))}
                      </div>

                      {/* Ref */}
                      <p className="text-earth-400 text-xs mt-2">
                        Ref #<strong>{b.id}</strong> · Booked{" "}
                        {b.createdAt ? new Date(b.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "—"}
                      </p>
                    </div>
                  </div>

                  {/* Action bar */}
                  <div className="border-t border-earth-100 px-4 py-3 bg-earth-50 flex items-center gap-2 flex-wrap">
                    <button
                      onClick={() => navigate(`/bookings/${b.id}`)}
                      className="flex-1 sm:flex-none bg-earth-900 hover:bg-earth-800 text-white text-xs font-medium px-4 py-2 rounded-lg transition-all"
                    >
                      View Full Details →
                    </button>
                    <button
                      onClick={() => handleDownload(b)}
                      className="text-earth-600 hover:text-earth-800 text-xs font-medium px-3 py-2 rounded-lg hover:bg-earth-100 transition-all border border-earth-200"
                    >
                      ⬇ Download Plan
                    </button>
                    {b.status !== "CANCELLED" && (
                      <button
                        onClick={() => setShowCancelModal(b)}
                        className="text-red-500 hover:text-red-700 text-xs font-medium px-3 py-2 rounded-lg hover:bg-red-50 transition-all border border-red-100"
                        disabled={cancellingId === b.id}
                      >
                        {cancellingId === b.id ? "Cancelling…" : "✗ Cancel Trip"}
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* ─── Cancel Confirmation Modal ─────────────────────────────── */}
      {showCancelModal && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center px-4">
          <div className="bg-white rounded-2xl p-6 max-w-sm w-full shadow-2xl">
            <div className="text-center mb-5">
              <div className="text-4xl mb-3">⚠️</div>
              <h3 className="font-display text-xl font-bold text-earth-900 mb-2">Cancel This Trip?</h3>
              <p className="text-earth-600 text-sm">
                Are you sure you want to cancel your trip to{" "}
                <strong>{showCancelModal.destination?.name}</strong>? This action cannot be undone.
              </p>
            </div>
            <div className="flex gap-3">
              <button
                onClick={() => setShowCancelModal(null)}
                className="flex-1 border border-earth-200 text-earth-700 py-2.5 rounded-xl text-sm font-medium hover:bg-earth-50 transition-all"
              >
                Keep Trip
              </button>
              <button
                onClick={() => handleCancel(showCancelModal.id)}
                className="flex-1 bg-red-600 hover:bg-red-700 text-white py-2.5 rounded-xl text-sm font-medium transition-all"
                disabled={cancellingId === showCancelModal.id}
              >
                {cancellingId === showCancelModal.id ? "Cancelling…" : "Yes, Cancel"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
